# Generated by Django 4.2.10 on 2024-03-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_rename_content_ticket_message_remove_ticket_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="subject",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="phone",
            field=models.CharField(max_length=11),
        ),
    ]
